apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (HEAD)
    traefik.enable: "false"
  creationTimestamp: null
  labels:
    io.kompose.service: telegraf
  name: telegraf
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: telegraf
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 (HEAD)
        traefik.enable: "false"
      creationTimestamp: null
      labels:
        io.kompose.network/src_connected: "true"
        io.kompose.network/src_hidden: "true"
        io.kompose.service: telegraf
    spec:
      containers:
      - image: telegraf
        imagePullPolicy: ""
        name: telegraf
        resources: {}
        volumeMounts:
        - mountPath: /etc/telegraf/telegraf.conf
          name: telegraf-claim0
      hostname: telegraf
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: telegraf-claim0
        persistentVolumeClaim:
          claimName: telegraf-claim0
status: {}
