global:
  scrape_interval:     15s
  evaluation_interval: 15s

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: docker-host-alpha

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
# rule_files:
#   - "alert.rules"

# A scrape configuration containing exactly one endpoint to scrape.
scrape_configs:
  - job_name: nodeexporter
    scrape_interval: 5s
    static_configs:
      - targets: ['sombra.home:9100', 'pi.home:9100', 'lucio.home:9100']
    tls_config:
      ca_file: '/etc/ca/rootCA.pem'


  - job_name: cadvisor
    scrape_interval: 5s
    static_configs:
      - targets: ['cadvisor:8080', 'cadvisor.pi.home', 'cadvisor.lucio.home']
    tls_config:
      ca_file: '/etc/ca/rootCA.pem'

  - job_name: prometheus
    scrape_interval: 10s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: pushgateway
    scrape_interval: 10s
    honor_labels: true
    static_configs:
      - targets: ['pushgateway:9091']

  - job_name: traefik
    scrape_interval: 10s
    honor_labels: true
    static_configs:
      - targets: ['traefik:8080', 'traefik.pi.home', 'traefik.lucio.home']
    tls_config:
      ca_file: '/etc/ca/rootCA.pem'

  - job_name: docker
    scrape_interval: 10s
    static_configs:
      - targets: ['sombra.home:42375', 'pi.home:42375', 'lucio.home:42375']

  - job_name: jenkins
    metrics_path: '/prometheus/'
    static_configs:
      - targets: ['jenkins:8080']

  - job_name: blackbox
    metrics_path: /probe
    params:
      module: [http_2xx]  # Look for a HTTP 200 response.
    static_configs:
      - targets:
        - http://vpn-client:9091
        - http://vpn-client:9000
        - http://vpn-client:3000
        # - http://prometheus.io    # Target to probe with http.
        # - https://prometheus.io   # Target to probe with https.
        # - http://example.com:8080 # Target to probe with http on port 8080.
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox:9115  # The blackbox exporter's real hostname:port.

  - job_name: mysql
    static_configs:
      - targets: ['mysqld-exporter:9104']

  - job_name: redis
    static_configs:
    - targets: ['redis-exporter:9121']

  - job_name: elasticsearch
    scrape_interval: 60s
    scrape_timeout:  30s
    metrics_path: "/metrics"
    static_configs:
    - targets:
      - elasticsearch-exporter:9114
      - elasticsearch-diskover-exporter:9114
      labels:
        service: elasticsearch
    relabel_configs:
    - source_labels: [__address__]
      regex: '(.*)\:9114'
      target_label:  'instance'
      replacement:   '$1'

  - job_name: transmission
    static_configs:
    - targets: ['transmission-exporter:19091']

  - job_name: minecraft
    static_configs:
    - targets: ['minecraft:9225']
      labels:
        server_name: 'minecraft'

  - job_name: rabbitmq
    static_configs:
    - targets: ['rabbitmq:9419']

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - 'alertmanager:9093'

#  - job_name: 'nginx'
#    scrape_interval: 10s
#    static_configs:
#      - targets: ['nginxexporter:9113']

#  - job_name: 'aspnetcore'
#    scrape_interval: 10s
#    static_configs:
#      - targets: ['eventlog-proxy:5000', 'eventlog:5000']
