apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert --volumes hostPath
    kompose.version: 1.21.0 (HEAD)
    traefik.enable: "false"
  creationTimestamp: null
  labels:
    io.kompose.service: logstash
  name: logstash
spec:
  ports:
  - name: "5044"
    port: 5044
    targetPort: 5044
  selector:
    io.kompose.service: logstash
status:
  loadBalancer: {}
