# This file is where you define your pipelines. You can define multiple.
# For more information on multiple pipelines, see the documentation:
#   https://www.elastic.co/guide/en/logstash/current/multiple-pipelines.html

- pipeline.id: to_rabbitmq
  path.config: "/usr/share/logstash/pipeline/to_rabbitmq.conf"
  pipeline.workers: 2
- pipeline.id: from_rabbitmq
  path.config: "/usr/share/logstash/pipeline/from_rabbitmq.conf"
  pipeline.workers: 2
